### PR TITLE
No.38 2022 0208 Heap 1st

### PR DESCRIPTION
**Pull request by the-yuyut**
# LeetCode 讀書會第 38 次聚會 2022/02/08

## leetcode 讀書會通知

1. 項目: 第 38 次聚會
2. 目的: 線上一起寫題目, 由有想法的人帶領, 先解題, 再看該題有趣的解法
3. 時間: 02/08 (二) 20:00 ~ 21:00
4. 地點: google meet 線上 (前 10 分鐘預備鏈接)
5. 解題項目:  [Heap](https://leetcode.com/explore/featured/card/heap/643/heap/)
6. 共筆: GitHub https://github.com/programmingbookclub/Leetcode-club
7. 備註: 

這次的主題 Heap 是 premium 限定，但是有活動可以解鎖，如果看不到的話請聯繫 Yu。這次第一次先來瀏覽大學課程的相關知識。請大家在留言提供你預習/記憶中想到的關於 Heap 的知識。

> LeetCode is offering a limited-time FREE offer for these great resources. The offer ends on Feb 14th. (2022)

--- 

* 	MEDIUM	215	Kth Largest Element in an Array	https://leetcode.com/problems/kth-largest-element-in-an-array
* 	MEDIUM	347	Top K Frequent Elements	https://leetcode.com/problems/top-k-frequent-elements
* 	EASY	703	Kth Largest Element in a Stream	https://leetcode.com/problems/kth-largest-element-in-a-stream
* 	EASY	1046	Last Stone Weight	https://leetcode.com/problems/last-stone-weight
* 	EASY	1337	The K Weakest Rows in a Matrix	https://leetcode.com/problems/the-k-weakest-rows-in-a-matrix
* 	MEDIUM	378	Kth Smallest Element in a Sorted Matrix	https://leetcode.com/problems/kth-smallest-element-in-a-sorted-matrix
* 	🔓	MEDIUM	253	Meeting Rooms II	https://leetcode.com/problems/meeting-rooms-ii
* 	MEDIUM	973	K Closest Points to Origin	https://leetcode.com/problems/k-closest-points-to-origin
* 	🔓	MEDIUM	1167	Minimum Cost to Connect Sticks	https://leetcode.com/problems/minimum-cost-to-connect-sticks
* 	MEDIUM	1642	Furthest Building You Can Reach	https://leetcode.com/problems/furthest-building-you-can-reach
* 	HARD	295	Find Median from Data Stream	https://leetcode.com/problems/find-median-from-data-stream

### CODE REVIEW

**Comment by the-yuyut** [comment]
補充 https://github.com/azl397985856/leetcode/blob/master/thinkings/heap-2.md

**Comment by ytyubox** [comment]
Heap 必須是 complete tree

**Comment by the-yuyut** [comment]
Name | Best | Average | Worst | Memory | Stable | Method
-- | -- | -- | -- | -- | -- | --
Heapsort | n log n | n log n | n log n  | 1 | No | Selection

**Comment by sharonWU0505** [comment]
- Heap 是一種特殊的 binary tree (complete or nearly complete)，它是 Priority Queue 的其中一種資料結構
- 有分 Max Heap 和 Min Heap
   - Max Heap: 每個節點的值不小於子節點的值
   - Min Heap: 每個節點的值不大於子節點的值
- 時間複雜度
   - 插入節點：O(log N)
   - 刪除節點：O(log N)
   - 取最大/最小值：~O(log N)~ O(1)

**Comment by the-yuyut** [comment]
```text
by Louis
我來試著憑記憶描述 Heap
Heap 是一種永遠維持著根節點為數值最小 (或最大) 的樹狀結構，
因此每一次從 Heap 取出最小值的都只需要 O(1) 的執行時間，i.e. 取得根節點
為了維持根節點的這個特性，每一次放入或取出新節點，都需要一些 Heap 特有的計算，來調整樹狀結構的順序，
同時，Heap 的節點必須是可以比較大小的
```

**Pull request merged**
